/*
 * Collection utility of String Struct
 *
 * Generated by: Go Streamer
 */

package sample

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type StringStream []String

func StringStreamOf(arg ...String) StringStream {
	return arg
}
func StringStreamFrom(arg []String) StringStream {
	return arg
}
func CreateStringStream(arg ...String) *StringStream {
	tmp := StringStreamOf(arg...)
	return &tmp
}
func GenerateStringStream(arg []String) *StringStream {
	tmp := StringStreamFrom(arg)
	return &tmp
}

func (self *StringStream) Add(arg String) *StringStream {
	return self.AddAll(arg)
}
func (self *StringStream) AddAll(arg ...String) *StringStream {
	*self = append(*self, arg...)
	return self
}
func (self *StringStream) AddSafe(arg *String) *StringStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *StringStream) Aggregate(fn func(String, String) String) *StringStream {
	result := StringStreamOf()
	self.ForEach(func(v String, i int) {
		if i == 0 {
			result.Add(fn(String{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *StringStream) AllMatch(fn func(String, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *StringStream) AnyMatch(fn func(String, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *StringStream) Clone() *StringStream {
	temp := make([]String, self.Len())
	copy(temp, *self)
	return (*StringStream)(&temp)
}
func (self *StringStream) Copy() *StringStream {
	return self.Clone()
}
func (self *StringStream) Concat(arg []String) *StringStream {
	return self.AddAll(arg...)
}
func (self *StringStream) Contains(arg String) bool {
	return self.FindIndex(func(_arg String, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *StringStream) Clean() *StringStream {
	*self = StringStreamOf()
	return self
}
func (self *StringStream) Delete(index int) *StringStream {
	return self.DeleteRange(index, index)
}
func (self *StringStream) DeleteRange(startIndex, endIndex int) *StringStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *StringStream) Distinct() *StringStream {
	caches := map[string]bool{}
	result := StringStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *StringStream) Each(fn func(String)) *StringStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *StringStream) EachRight(fn func(String)) *StringStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *StringStream) Equals(arr []String) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *StringStream) Filter(fn func(String, int) bool) *StringStream {
	result := StringStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *StringStream) FilterSlim(fn func(String, int) bool) *StringStream {
	result := StringStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *StringStream) Find(fn func(String, int) bool) *String {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *StringStream) FindOr(fn func(String, int) bool, or String) String {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *StringStream) FindIndex(fn func(String, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *StringStream) First() *String {
	return self.Get(0)
}
func (self *StringStream) FirstOr(arg String) String {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *StringStream) ForEach(fn func(String, int)) *StringStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *StringStream) ForEachRight(fn func(String, int)) *StringStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *StringStream) GroupBy(fn func(String, int) string) map[string][]String {
	m := map[string][]String{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *StringStream) GroupByValues(fn func(String, int) string) [][]String {
	var tmp [][]String
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *StringStream) IndexOf(arg String) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *StringStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *StringStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *StringStream) Last() *String {
	return self.Get(self.Len() - 1)
}
func (self *StringStream) LastOr(arg String) String {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *StringStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *StringStream) Limit(limit int) *StringStream {
	self.Slice(0, limit)
	return self
}

func (self *StringStream) Map(fn func(String, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Int(fn func(String, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Int32(fn func(String, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Int64(fn func(String, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Float32(fn func(String, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Float64(fn func(String, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Bool(fn func(String, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2Bytes(fn func(String, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Map2String(fn func(String, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *StringStream) Max(fn func(String, int) float64) *String {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *StringStream) Min(fn func(String, int) float64) *String {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *StringStream) NoneMatch(fn func(String, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *StringStream) Get(index int) *String {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *StringStream) GetOr(index int, arg String) String {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *StringStream) Peek(fn func(*String, int)) *StringStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *StringStream) Reduce(fn func(String, String, int) String) *StringStream {
	return self.ReduceInit(fn, String{})
}
func (self *StringStream) ReduceInit(fn func(String, String, int) String, initialValue String) *StringStream {
	result := StringStreamOf()
	self.ForEach(func(v String, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *StringStream) ReduceInterface(fn func(interface{}, String, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(String{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceString(fn func(string, String, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceInt(fn func(int, String, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceInt32(fn func(int32, String, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceInt64(fn func(int64, String, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceFloat32(fn func(float32, String, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceFloat64(fn func(float64, String, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) ReduceBool(fn func(bool, String, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *StringStream) Reverse() *StringStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *StringStream) Replace(fn func(String, int) String) *StringStream {
	return self.ForEach(func(v String, i int) { self.Set(i, fn(v, i)) })
}
func (self *StringStream) Select(fn func(String) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *StringStream) Set(index int, val String) *StringStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *StringStream) Skip(skip int) *StringStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *StringStream) SkippingEach(fn func(String, int) int) *StringStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *StringStream) Slice(startIndex, n int) *StringStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []String{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *StringStream) Sort(fn func(i, j int) bool) *StringStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *StringStream) Tail() *String {
	return self.Last()
}
func (self *StringStream) TailOr(arg String) String {
	return self.LastOr(arg)
}
func (self *StringStream) ToList() []String {
	return self.Val()
}
func (self *StringStream) Unique() *StringStream {
	return self.Distinct()
}
func (self *StringStream) Val() []String {
	if self == nil {
		return []String{}
	}
	return *self.Copy()
}
func (self *StringStream) While(fn func(String, int) bool) *StringStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *StringStream) Where(fn func(String) bool) *StringStream {
	result := StringStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *StringStream) WhereSlim(fn func(String) bool) *StringStream {
	result := StringStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
