/*
 * Collection utility of Integer Struct
 *
 * Generated by: Go Streamer
 */

package sample

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type IntegerStream []Integer

func IntegerStreamOf(arg ...Integer) IntegerStream {
	return arg
}
func IntegerStreamFrom(arg []Integer) IntegerStream {
	return arg
}
func CreateIntegerStream(arg ...Integer) *IntegerStream {
	tmp := IntegerStreamOf(arg...)
	return &tmp
}
func GenerateIntegerStream(arg []Integer) *IntegerStream {
	tmp := IntegerStreamFrom(arg)
	return &tmp
}

func (self *IntegerStream) Add(arg Integer) *IntegerStream {
	return self.AddAll(arg)
}
func (self *IntegerStream) AddAll(arg ...Integer) *IntegerStream {
	*self = append(*self, arg...)
	return self
}
func (self *IntegerStream) AddSafe(arg *Integer) *IntegerStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *IntegerStream) Aggregate(fn func(Integer, Integer) Integer) *IntegerStream {
	result := IntegerStreamOf()
	self.ForEach(func(v Integer, i int) {
		if i == 0 {
			result.Add(fn(Integer{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *IntegerStream) AllMatch(fn func(Integer, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *IntegerStream) AnyMatch(fn func(Integer, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *IntegerStream) Clone() *IntegerStream {
	temp := make([]Integer, self.Len())
	copy(temp, *self)
	return (*IntegerStream)(&temp)
}
func (self *IntegerStream) Copy() *IntegerStream {
	return self.Clone()
}
func (self *IntegerStream) Concat(arg []Integer) *IntegerStream {
	return self.AddAll(arg...)
}
func (self *IntegerStream) Contains(arg Integer) bool {
	return self.FindIndex(func(_arg Integer, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *IntegerStream) Clean() *IntegerStream {
	*self = IntegerStreamOf()
	return self
}
func (self *IntegerStream) Delete(index int) *IntegerStream {
	return self.DeleteRange(index, index)
}
func (self *IntegerStream) DeleteRange(startIndex, endIndex int) *IntegerStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *IntegerStream) Distinct() *IntegerStream {
	caches := map[string]bool{}
	result := IntegerStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *IntegerStream) Each(fn func(Integer)) *IntegerStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *IntegerStream) EachRight(fn func(Integer)) *IntegerStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *IntegerStream) Equals(arr []Integer) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *IntegerStream) Filter(fn func(Integer, int) bool) *IntegerStream {
	result := IntegerStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *IntegerStream) FilterSlim(fn func(Integer, int) bool) *IntegerStream {
	result := IntegerStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *IntegerStream) Find(fn func(Integer, int) bool) *Integer {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *IntegerStream) FindOr(fn func(Integer, int) bool, or Integer) Integer {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *IntegerStream) FindIndex(fn func(Integer, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *IntegerStream) First() *Integer {
	return self.Get(0)
}
func (self *IntegerStream) FirstOr(arg Integer) Integer {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *IntegerStream) ForEach(fn func(Integer, int)) *IntegerStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *IntegerStream) ForEachRight(fn func(Integer, int)) *IntegerStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *IntegerStream) GroupBy(fn func(Integer, int) string) map[string][]Integer {
	m := map[string][]Integer{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *IntegerStream) GroupByValues(fn func(Integer, int) string) [][]Integer {
	var tmp [][]Integer
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *IntegerStream) IndexOf(arg Integer) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *IntegerStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *IntegerStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *IntegerStream) Last() *Integer {
	return self.Get(self.Len() - 1)
}
func (self *IntegerStream) LastOr(arg Integer) Integer {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *IntegerStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *IntegerStream) Limit(limit int) *IntegerStream {
	self.Slice(0, limit)
	return self
}

func (self *IntegerStream) Map(fn func(Integer, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Int(fn func(Integer, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Int32(fn func(Integer, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Int64(fn func(Integer, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Float32(fn func(Integer, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Float64(fn func(Integer, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Bool(fn func(Integer, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2Bytes(fn func(Integer, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Map2String(fn func(Integer, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *IntegerStream) Max(fn func(Integer, int) float64) *Integer {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *IntegerStream) Min(fn func(Integer, int) float64) *Integer {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *IntegerStream) NoneMatch(fn func(Integer, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *IntegerStream) Get(index int) *Integer {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *IntegerStream) GetOr(index int, arg Integer) Integer {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *IntegerStream) Peek(fn func(*Integer, int)) *IntegerStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *IntegerStream) Reduce(fn func(Integer, Integer, int) Integer) *IntegerStream {
	return self.ReduceInit(fn, Integer{})
}
func (self *IntegerStream) ReduceInit(fn func(Integer, Integer, int) Integer, initialValue Integer) *IntegerStream {
	result := IntegerStreamOf()
	self.ForEach(func(v Integer, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *IntegerStream) ReduceInterface(fn func(interface{}, Integer, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(Integer{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceString(fn func(string, Integer, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceInt(fn func(int, Integer, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceInt32(fn func(int32, Integer, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceInt64(fn func(int64, Integer, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceFloat32(fn func(float32, Integer, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceFloat64(fn func(float64, Integer, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) ReduceBool(fn func(bool, Integer, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *IntegerStream) Reverse() *IntegerStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *IntegerStream) Replace(fn func(Integer, int) Integer) *IntegerStream {
	return self.ForEach(func(v Integer, i int) { self.Set(i, fn(v, i)) })
}
func (self *IntegerStream) Select(fn func(Integer) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *IntegerStream) Set(index int, val Integer) *IntegerStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *IntegerStream) Skip(skip int) *IntegerStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *IntegerStream) SkippingEach(fn func(Integer, int) int) *IntegerStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *IntegerStream) Slice(startIndex, n int) *IntegerStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []Integer{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *IntegerStream) Sort(fn func(i, j int) bool) *IntegerStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *IntegerStream) Tail() *Integer {
	return self.Last()
}
func (self *IntegerStream) TailOr(arg Integer) Integer {
	return self.LastOr(arg)
}
func (self *IntegerStream) ToList() []Integer {
	return self.Val()
}
func (self *IntegerStream) Unique() *IntegerStream {
	return self.Distinct()
}
func (self *IntegerStream) Val() []Integer {
	if self == nil {
		return []Integer{}
	}
	return *self.Copy()
}
func (self *IntegerStream) While(fn func(Integer, int) bool) *IntegerStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *IntegerStream) Where(fn func(Integer) bool) *IntegerStream {
	result := IntegerStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *IntegerStream) WhereSlim(fn func(Integer) bool) *IntegerStream {
	result := IntegerStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
